// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://majpukxhyyetfukmmktr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1hanB1a3hoeXlldGZ1a21ta3RyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNDgxMzksImV4cCI6MjA2NzYyNDEzOX0.X0WSB0mhs_OY_hb9V4usPU1s4j599Zgbr2JxgNoX7WM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});